name: Node CI

on:
  push:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
        env:
          NODE_ENV: development

      - run: npm run lint
      - run: npm run build
